"""
抖音商城模拟数据 - 商品库、店铺信息、价格历史
完全模拟真实电商数据结构，供AI购物智能体调用
"""

# 商品数据库（模拟抖音商城商品池）
PRODUCT_DB = {
    # ==================== 手机类 ====================
    "iphone15_001": {
        "product_id": "iphone15_001",
        "name": "Apple iPhone 15 128GB 黑色",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "Apple",
        "price": 5999,
        "original_price": 6999,
        "discount": "满5999减200",
        "shop_id": "shop_apple_001",
        "is_official": True,
        "sales_volume": "10万+",
        "rating": 4.8,
        "specs": {
            "processor": "A16仿生芯片",
            "screen": "6.1英寸 OLED",
            "camera": "4800万主摄",
            "battery": "3349mAh",
            "weight": "171g",
            "os": "iOS 17"
        },
        "tags": ["官方正品", "全国联保", "12期免息"],
        "good_reviews": ["拍照清晰", "系统流畅", "手感好"],
        "bad_reviews": ["续航一般", "信号不稳定", "充电慢"],
        "price_history": {
            "30d_min": 5399,
            "30d_avg": 5699,
            "30d_max": 6199,
            "lowest_ever": 5299
        },
        "stock": 589,
        "delivery": "次日达"
    },
    
    "xiaomi14_002": {
        "product_id": "xiaomi14_002",
        "name": "小米14 16+512GB 白色",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "小米",
        "price": 4599,
        "original_price": 4999,
        "discount": "领券减100",
        "shop_id": "shop_xiaomi_001",
        "is_official": True,
        "sales_volume": "5万+",
        "rating": 4.7,
        "specs": {
            "processor": "骁龙8 Gen3",
            "screen": "6.36英寸 1.5K",
            "camera": "徕卡三摄 5000万",
            "battery": "4610mAh",
            "weight": "188g",
            "os": "HyperOS"
        },
        "tags": ["徕卡联名", "90W快充", "IP68"],
        "good_reviews": ["拍照好看", "充电快", "手感小屏"],
        "bad_reviews": ["MIUI广告多", "发热略明显", "电池不耐用"],
        "price_history": {
            "30d_min": 4199,
            "30d_avg": 4399,
            "30d_max": 4699,
            "lowest_ever": 3999
        },
        "stock": 324,
        "delivery": "明日达"
    },
    
    "huawei60_003": {
        "product_id": "huawei60_003",
        "name": "华为 Mate 60 Pro 12+512GB 雅川青",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "华为",
        "price": 6999,
        "original_price": 7999,
        "discount": "赠碎屏险",
        "shop_id": "shop_huawei_001",
        "is_official": True,
        "sales_volume": "8万+",
        "rating": 4.9,
        "specs": {
            "processor": "麒麟9000S",
            "screen": "6.82英寸 OLED",
            "camera": "XMAGE影像 5000万",
            "battery": "5000mAh",
            "weight": "225g",
            "os": "HarmonyOS 4"
        },
        "tags": ["卫星通话", "昆仑玻璃", "鸿蒙系统"],
        "good_reviews": ["信号强", "系统流畅", "拍照真实"],
        "bad_reviews": ["重", "发热", "价格高"],
        "price_history": {
            "30d_min": 6799,
            "30d_avg": 6999,
            "30d_max": 7299,
            "lowest_ever": 6699
        },
        "stock": 127,
        "delivery": "预订7天"
    },
        # ==================== 新增手机产品 ====================
    "iphone15_pro_008": {
        "product_id": "iphone15_pro_008",
        "name": "Apple iPhone 15 Pro 256GB 原色钛金属",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "Apple",
        "price": 8999,
        "original_price": 9999,
        "discount": "限时立减1000",
        "shop_id": "shop_apple_001",
        "is_official": True,
        "sales_volume": "8万+",
        "rating": 4.9,
        "specs": {"processor": "A17 Pro", "screen": "6.1英寸 OLED 120Hz", "camera": "4800万主摄+长焦", "battery": "3274mAh", "weight": "187g", "os": "iOS 17"},
        "tags": ["钛金属", "Action按键", "USB-C 3.0"],
        "good_reviews": ["手感好", "拍照强", "性能过剩"],
        "bad_reviews": ["贵", "发热", "续航一般"],
        "price_history": {"30d_min": 8499, "30d_avg": 8999, "30d_max": 9499, "lowest_ever": 8299},
        "stock": 234,
        "delivery": "次日达"
    },
    "iphone15_plus_009": {
        "product_id": "iphone15_plus_009",
        "name": "Apple iPhone 15 Plus 128GB 粉色",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "Apple",
        "price": 6999,
        "original_price": 7999,
        "discount": "12期免息",
        "shop_id": "shop_apple_001",
        "is_official": True,
        "sales_volume": "5万+",
        "rating": 4.7,
        "specs": {"processor": "A16", "screen": "6.7英寸 OLED", "camera": "4800万主摄", "battery": "4383mAh", "weight": "201g", "os": "iOS 17"},
        "tags": ["大屏", "长续航", "灵动岛"],
        "good_reviews": ["屏幕大", "电池耐用", "颜色好看"],
        "bad_reviews": ["60Hz屏幕", "重", "充电慢"],
        "price_history": {"30d_min": 6499, "30d_avg": 6999, "30d_max": 7499, "lowest_ever": 6399},
        "stock": 567,
        "delivery": "次日达"
    },
    "xiaomi14_pro_010": {
        "product_id": "xiaomi14_pro_010",
        "name": "小米14 Pro 16+1TB 钛金属特别版",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "小米",
        "price": 6999,
        "original_price": 7499,
        "discount": "赠礼盒",
        "shop_id": "shop_xiaomi_001",
        "is_official": True,
        "sales_volume": "2万+",
        "rating": 4.8,
        "specs": {"processor": "骁龙8 Gen3", "screen": "6.73英寸 2K 120Hz", "camera": "徕卡四摄", "battery": "4880mAh", "weight": "223g", "os": "HyperOS"},
        "tags": ["2K屏幕", "120W快充", "龙晶玻璃"],
        "good_reviews": ["屏幕好", "拍照强", "充电快"],
        "bad_reviews": ["重", "系统广告", "价格高"],
        "price_history": {"30d_min": 6499, "30d_avg": 6999, "30d_max": 7299, "lowest_ever": 6299},
        "stock": 145,
        "delivery": "明日达"
    },
    "redmi_k70_011": {
        "product_id": "redmi_k70_011",
        "name": "红米 K70 12+256GB 墨羽",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "小米",
        "price": 2499,
        "original_price": 2699,
        "discount": "立减200",
        "shop_id": "shop_xiaomi_001",
        "is_official": True,
        "sales_volume": "20万+",
        "rating": 4.6,
        "specs": {"processor": "骁龙8 Gen2", "screen": "6.67英寸 2K 120Hz", "camera": "6400万主摄", "battery": "5000mAh", "weight": "209g", "os": "HyperOS"},
        "tags": ["2K直屏", "5000mAh", "性价比"],
        "good_reviews": ["屏幕清晰", "续航好", "性能强"],
        "bad_reviews": ["塑料中框", "拍照一般", "系统广告"],
        "price_history": {"30d_min": 2299, "30d_avg": 2499, "30d_max": 2599, "lowest_ever": 2199},
        "stock": 1234,
        "delivery": "次日达"
    },
    "huawei_pura70_012": {
        "product_id": "huawei_pura70_012",
        "name": "华为 Pura 70 12+512GB 樱玫红",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "华为",
        "price": 5999,
        "original_price": 6499,
        "discount": "赠充电器",
        "shop_id": "shop_huawei_001",
        "is_official": True,
        "sales_volume": "6万+",
        "rating": 4.8,
        "specs": {"processor": "麒麟9000S1", "screen": "6.6英寸 OLED", "camera": "5000万超聚光", "battery": "4900mAh", "weight": "207g", "os": "HarmonyOS 4"},
        "tags": ["超聚光影像", "卫星消息", "北斗"],
        "good_reviews": ["拍照好", "信号强", "系统流畅"],
        "bad_reviews": ["价格高", "发热", "充电慢"],
        "price_history": {"30d_min": 5699, "30d_avg": 5999, "30d_max": 6299, "lowest_ever": 5599},
        "stock": 321,
        "delivery": "预订5天"
    },
    "honor_magic6_013": {
        "product_id": "honor_magic6_013",
        "name": "荣耀 Magic6 16+512GB 海湖青",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "荣耀",
        "price": 4999,
        "original_price": 5499,
        "discount": "送耳机",
        "shop_id": "shop_honor_001",
        "is_official": True,
        "sales_volume": "4万+",
        "rating": 4.7,
        "specs": {"processor": "骁龙8 Gen3", "screen": "6.78英寸 120Hz", "camera": "5000万鹰眼", "battery": "5450mAh", "weight": "206g", "os": "MagicOS"},
        "tags": ["巨犀玻璃", "鹰眼抓拍", "大电池"],
        "good_reviews": ["续航强", "信号好", "拍照清晰"],
        "bad_reviews": ["系统更新慢", "屏幕护眼一般"],
        "price_history": {"30d_min": 4599, "30d_avg": 4999, "30d_max": 5299, "lowest_ever": 4499},
        "stock": 478,
        "delivery": "次日达"
    },
    "oppo_find_x7_014": {
        "product_id": "oppo_find_x7_014",
        "name": "OPPO Find X7 12+256GB 海阔天空",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "OPPO",
        "price": 3999,
        "original_price": 4499,
        "discount": "24期免息",
        "shop_id": "shop_oppo_001",
        "is_official": True,
        "sales_volume": "3万+",
        "rating": 4.7,
        "specs": {"processor": "天玑9300", "screen": "6.78英寸 1.5K", "camera": "5000万哈苏", "battery": "5000mAh", "weight": "202g", "os": "ColorOS"},
        "tags": ["哈苏影像", "100W快充", "IP68"],
        "good_reviews": ["拍照好看", "充电快", "系统流畅"],
        "bad_reviews": ["续航一般", "屏幕调色偏", "价格跳水"],
        "price_history": {"30d_min": 3799, "30d_avg": 3999, "30d_max": 4199, "lowest_ever": 3699},
        "stock": 653,
        "delivery": "明日达"
    },
    "vivo_x100_015": {
        "product_id": "vivo_x100_015",
        "name": "vivo X100 12+256GB 落日橙",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "vivo",
        "price": 4499,
        "original_price": 4999,
        "discount": "赠背包",
        "shop_id": "shop_vivo_001",
        "is_official": True,
        "sales_volume": "5万+",
        "rating": 4.8,
        "specs": {"processor": "天玑9300", "screen": "6.78英寸 1.5K", "camera": "5000万蔡司", "battery": "5000mAh", "weight": "202g", "os": "OriginOS"},
        "tags": ["蔡司影像", "120W快充", "IP68"],
        "good_reviews": ["拍照无敌", "续航好", "系统流畅"],
        "bad_reviews": ["屏幕塑料感", "重量大", "价格高"],
        "price_history": {"30d_min": 4299, "30d_avg": 4499, "30d_max": 4799, "lowest_ever": 4199},
        "stock": 512,
        "delivery": "次日达"
    },
    "samsung_s24_016": {
        "product_id": "samsung_s24_016",
        "name": "三星 Galaxy S24 8+256GB 水墨黑",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "三星",
        "price": 5499,
        "original_price": 5999,
        "discount": "立减500",
        "shop_id": "shop_samsung_001",
        "is_official": True,
        "sales_volume": "2万+",
        "rating": 4.6,
        "specs": {"processor": "骁龙8 Gen3", "screen": "6.2英寸 120Hz", "camera": "5000万主摄", "battery": "4000mAh", "weight": "167g", "os": "One UI"},
        "tags": ["AI功能", "小屏旗舰", "7年更新"],
        "good_reviews": ["手感好", "屏幕顶级", "AI实用"],
        "bad_reviews": ["电池小", "充电慢", "价格高"],
        "price_history": {"30d_min": 5199, "30d_avg": 5499, "30d_max": 5799, "lowest_ever": 4999},
        "stock": 189,
        "delivery": "次日达"
    },
    "oneplus_12_017": {
        "product_id": "oneplus_12_017",
        "name": "一加 12 16+512GB 苍绿",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "一加",
        "price": 4799,
        "original_price": 5299,
        "discount": "学生优惠100",
        "shop_id": "shop_oneplus_001",
        "is_official": True,
        "sales_volume": "3万+",
        "rating": 4.8,
        "specs": {"processor": "骁龙8 Gen3", "screen": "6.82英寸 2K 120Hz", "camera": "5000万哈苏", "battery": "5400mAh", "weight": "220g", "os": "ColorOS"},
        "tags": ["2K东方屏", "大电池", "仿生振感马达"],
        "good_reviews": ["屏幕好", "续航强", "马达爽"],
        "bad_reviews": ["重", "曲面屏误触", "系统广告"],
        "price_history": {"30d_min": 4499, "30d_avg": 4799, "30d_max": 4999, "lowest_ever": 4399},
        "stock": 342,
        "delivery": "次日达"
    },
    "realme_gt5pro_018": {
        "product_id": "realme_gt5pro_018",
        "name": "realme GT5 Pro 12+256GB 赤岩",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "realme",
        "price": 3299,
        "original_price": 3599,
        "discount": "预售立减",
        "shop_id": "shop_realme_001",
        "is_official": True,
        "sales_volume": "1万+",
        "rating": 4.5,
        "specs": {"processor": "骁龙8 Gen3", "screen": "6.78英寸 1.5K", "camera": "5000万主摄", "battery": "5400mAh", "weight": "218g", "os": "realme UI"},
        "tags": ["5400mAh", "100W快充", "50W无线"],
        "good_reviews": ["续航强", "充电快", "性价比高"],
        "bad_reviews": ["系统体验一般", "拍照普通", "重量大"],
        "price_history": {"30d_min": 2999, "30d_avg": 3299, "30d_max": 3499, "lowest_ever": 2899},
        "stock": 876,
        "delivery": "明日达"
    },
    "iqoo_12_019": {
        "product_id": "iqoo_12_019",
        "name": "iQOO 12 16+512GB 赛道版",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "iQOO",
        "price": 3999,
        "original_price": 4299,
        "discount": "赠耳机",
        "shop_id": "shop_iqoo_001",
        "is_official": True,
        "sales_volume": "4万+",
        "rating": 4.7,
        "specs": {"processor": "骁龙8 Gen3", "screen": "6.78英寸 1.5K", "camera": "5000万主摄", "battery": "5000mAh", "weight": "203g", "os": "OriginOS"},
        "tags": ["自研芯片Q1", "120W快充", "电竞体验"],
        "good_reviews": ["游戏流畅", "充电快", "散热好"],
        "bad_reviews": ["系统广告", "拍照一般", "塑料中框"],
        "price_history": {"30d_min": 3799, "30d_avg": 3999, "30d_max": 4199, "lowest_ever": 3699},
        "stock": 654,
        "delivery": "次日达"
    },
    "meizu_21_020": {
        "product_id": "meizu_21_020",
        "name": "魅族21 12+256GB 魅族白",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "魅族",
        "price": 3699,
        "original_price": 3999,
        "discount": "6期免息",
        "shop_id": "shop_meizu_001",
        "is_official": True,
        "sales_volume": "1万+",
        "rating": 4.5,
        "specs": {"processor": "骁龙8 Gen3", "screen": "6.55英寸 120Hz", "camera": "2亿像素主摄", "battery": "4800mAh", "weight": "198g", "os": "Flyme"},
        "tags": ["白色面板", "无广告", "超声波指纹"],
        "good_reviews": ["系统干净", "手感好", "指纹快"],
        "bad_reviews": ["拍照一般", "续航一般", "售后少"],
        "price_history": {"30d_min": 3499, "30d_avg": 3699, "30d_max": 3899, "lowest_ever": 3399},
        "stock": 234,
        "delivery": "次日达"
    },
    "nubia_z60_021": {
        "product_id": "nubia_z60_021",
        "name": "努比亚 Z60 Ultra 16+512GB 星空典藏版",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "努比亚",
        "price": 4999,
        "original_price": 5499,
        "discount": "12期免息",
        "shop_id": "shop_nubia_001",
        "is_official": True,
        "sales_volume": "5000+",
        "rating": 4.6,
        "specs": {"processor": "骁龙8 Gen3", "screen": "6.8英寸 真全面屏", "camera": "5000万三主摄", "battery": "6000mAh", "weight": "246g", "os": "MyOS"},
        "tags": ["屏下摄像", "6000mAh", "IP68"],
        "good_reviews": ["真全面屏", "续航巨好", "拍照强"],
        "bad_reviews": ["太重", "系统小众", "厚重"],
        "price_history": {"30d_min": 4699, "30d_avg": 4999, "30d_max": 5299, "lowest_ever": 4599},
        "stock": 98,
        "delivery": "次日达"
    },
    "moto_x40_022": {
        "product_id": "moto_x40_022",
        "name": "摩托罗拉 moto X40 12+256GB 墨韵黑",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "摩托罗拉",
        "price": 2799,
        "original_price": 2999,
        "discount": "立减200",
        "shop_id": "shop_moto_001",
        "is_official": True,
        "sales_volume": "8000+",
        "rating": 4.3,
        "specs": {"processor": "骁龙8 Gen2", "screen": "6.7英寸 165Hz", "camera": "5000万主摄", "battery": "4600mAh", "weight": "197g", "os": "MYUI"},
        "tags": ["165Hz高刷", "IP68", "无线充电"],
        "good_reviews": ["性价比高", "屏幕流畅", "系统简洁"],
        "bad_reviews": ["系统更新慢", "拍照一般", "售后少"],
        "price_history": {"30d_min": 2599, "30d_avg": 2799, "30d_max": 2899, "lowest_ever": 2499},
        "stock": 567,
        "delivery": "次日达"
    },
    "sony_xperia1_023": {
        "product_id": "sony_xperia1_023",
        "name": "索尼 Xperia 1 V 12+256GB 夜黑",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "Sony",
        "price": 8999,
        "original_price": 9999,
        "discount": "送存储卡",
        "shop_id": "shop_sony_002",
        "is_official": True,
        "sales_volume": "2000+",
        "rating": 4.4,
        "specs": {"processor": "骁龙8 Gen2", "screen": "6.5英寸 4K 120Hz", "camera": "1200万三摄", "battery": "5000mAh", "weight": "187g", "os": "Android 13"},
        "tags": ["4K屏", "3.5mm耳机孔", "微单体验"],
        "good_reviews": ["屏幕顶级", "拍照专业", "手感好"],
        "bad_reviews": ["系统原生难用", "价格高", "续航一般"],
        "price_history": {"30d_min": 8499, "30d_avg": 8999, "30d_max": 9499, "lowest_ever": 8299},
        "stock": 45,
        "delivery": "预订10天"
    },
    "honor_x50_024": {
        "product_id": "honor_x50_024",
        "name": "荣耀 X50 8+128GB 燃橙色",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "荣耀",
        "price": 1399,
        "original_price": 1499,
        "discount": "立减100",
        "shop_id": "shop_honor_001",
        "is_official": True,
        "sales_volume": "30万+",
        "rating": 4.5,
        "specs": {"processor": "骁龙6 Gen1", "screen": "6.78英寸 1.5K", "camera": "1亿像素", "battery": "5800mAh", "weight": "185g", "os": "MagicOS"},
        "tags": ["5800mAh", "1亿像素", "耐摔"],
        "good_reviews": ["续航超长", "屏幕好", "便宜"],
        "bad_reviews": ["性能弱", "充电慢", "塑料机身"],
        "price_history": {"30d_min": 1299, "30d_avg": 1399, "30d_max": 1449, "lowest_ever": 1199},
        "stock": 2345,
        "delivery": "次日达"
    },
    "oppo_reno11_025": {
        "product_id": "oppo_reno11_025",
        "name": "OPPO Reno11 12+256GB 月光宝石",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "OPPO",
        "price": 2799,
        "original_price": 2999,
        "discount": "6期免息",
        "shop_id": "shop_oppo_001",
        "is_official": True,
        "sales_volume": "8万+",
        "rating": 4.6,
        "specs": {"processor": "天玑8200", "screen": "6.7英寸 120Hz", "camera": "5000万单反级人像", "battery": "4800mAh", "weight": "184g", "os": "ColorOS"},
        "tags": ["人像专家", "轻薄", "67W快充"],
        "good_reviews": ["拍照好看", "手感轻薄", "系统流畅"],
        "bad_reviews": ["性能一般", "塑料中框", "续航普通"],
        "price_history": {"30d_min": 2599, "30d_avg": 2799, "30d_max": 2899, "lowest_ever": 2499},
        "stock": 876,
        "delivery": "次日达"
    },
    "vivo_s18_026": {
        "product_id": "vivo_s18_026",
        "name": "vivo S18 12+256GB 花似锦",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "vivo",
        "price": 2599,
        "original_price": 2799,
        "discount": "赠耳机",
        "shop_id": "shop_vivo_001",
        "is_official": True,
        "sales_volume": "6万+",
        "rating": 4.6,
        "specs": {"processor": "骁龙7 Gen3", "screen": "6.78英寸 1.5K", "camera": "5000万人像", "battery": "5000mAh", "weight": "185g", "os": "OriginOS"},
        "tags": ["影棚级人像", "5000mAh", "轻薄"],
        "good_reviews": ["拍照好", "手感轻", "续航不错"],
        "bad_reviews": ["性能中等", "充电慢", "系统广告"],
        "price_history": {"30d_min": 2399, "30d_avg": 2599, "30d_max": 2699, "lowest_ever": 2299},
        "stock": 743,
        "delivery": "次日达"
    },
    "redmi_note13_027": {
        "product_id": "redmi_note13_027",
        "name": "红米 Note 13 Pro+ 12+256GB 镜瓷白",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "小米",
        "price": 1899,
        "original_price": 1999,
        "discount": "满减100",
        "shop_id": "shop_xiaomi_001",
        "is_official": True,
        "sales_volume": "15万+",
        "rating": 4.5,
        "specs": {"processor": "天玑7200-Ultra", "screen": "6.67英寸 1.5K 120Hz", "camera": "2亿像素", "battery": "5000mAh", "weight": "204g", "os": "HyperOS"},
        "tags": ["2亿像素", "120W快充", "IP68"],
        "good_reviews": ["充电快", "屏幕好", "拍照清晰"],
        "bad_reviews": ["性能中端", "机身重", "发热"],
        "price_history": {"30d_min": 1699, "30d_avg": 1899, "30d_max": 1949, "lowest_ever": 1599},
        "stock": 1876,
        "delivery": "次日达"
    },
    "huawei_nova12_028": {
        "product_id": "huawei_nova12_028",
        "name": "华为 nova 12 Pro 12+256GB 12号色",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "华为",
        "price": 3999,
        "original_price": 4299,
        "discount": "赠自拍杆",
        "shop_id": "shop_huawei_001",
        "is_official": True,
        "sales_volume": "5万+",
        "rating": 4.7,
        "specs": {"processor": "麒麟8000", "screen": "6.76英寸 120Hz", "camera": "5000万物理可变光圈", "battery": "4600mAh", "weight": "193g", "os": "HarmonyOS 4"},
        "tags": ["前置双摄", "物理可变光圈", "鸿蒙"],
        "good_reviews": ["自拍好", "系统流畅", "信号强"],
        "bad_reviews": ["性能一般", "充电慢", "价格高"],
        "price_history": {"30d_min": 3799, "30d_avg": 3999, "30d_max": 4199, "lowest_ever": 3699},
        "stock": 432,
        "delivery": "次日达"
    },
    "samsung_a55_029": {
        "product_id": "samsung_a55_029",
        "name": "三星 Galaxy A55 8+256GB 冰蓝",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "三星",
        "price": 2999,
        "original_price": 3299,
        "discount": "立减300",
        "shop_id": "shop_samsung_001",
        "is_official": True,
        "sales_volume": "3万+",
        "rating": 4.4,
        "specs": {"processor": "Exynos 1480", "screen": "6.6英寸 120Hz", "camera": "5000万主摄", "battery": "5000mAh", "weight": "213g", "os": "One UI"},
        "tags": ["金属中框", "IP67", "大电池"],
        "good_reviews": ["质感好", "续航强", "屏幕亮"],
        "bad_reviews": ["性能中端", "充电慢", "系统卡"],
        "price_history": {"30d_min": 2799, "30d_avg": 2999, "30d_max": 3199, "lowest_ever": 2699},
        "stock": 654,
        "delivery": "次日达"
    },
    "oneplus_ace3_030": {
        "product_id": "oneplus_ace3_030",
        "name": "一加 Ace 3 16+512GB 月海蓝",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "一加",
        "price": 2999,
        "original_price": 3299,
        "discount": "学生优惠100",
        "shop_id": "shop_oneplus_001",
        "is_official": True,
        "sales_volume": "8万+",
        "rating": 4.7,
        "specs": {"processor": "骁龙8 Gen2", "screen": "6.78英寸 1.5K 120Hz", "camera": "5000万主摄", "battery": "5500mAh", "weight": "207g", "os": "ColorOS"},
        "tags": ["5500mAh", "100W快充", "金属中框"],
        "good_reviews": ["续航强", "充电快", "屏幕好"],
        "bad_reviews": ["系统广告", "拍照一般", "重"],
        "price_history": {"30d_min": 2799, "30d_avg": 2999, "30d_max": 3199, "lowest_ever": 2699},
        "stock": 945,
        "delivery": "次日达"
    },
    "realme_12pro_031": {
        "product_id": "realme_12pro_031",
        "name": "realme 12 Pro+ 12+256GB 深海潜航",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "realme",
        "price": 1999,
        "original_price": 2199,
        "discount": "立减200",
        "shop_id": "shop_realme_001",
        "is_official": True,
        "sales_volume": "4万+",
        "rating": 4.5,
        "specs": {"processor": "骁龙7s Gen2", "screen": "6.7英寸 120Hz", "camera": "6400万潜望长焦", "battery": "5000mAh", "weight": "196g", "os": "realme UI"},
        "tags": ["潜望长焦", "曲面屏", "轻薄"],
        "good_reviews": ["拍照好", "手感好", "续航不错"],
        "bad_reviews": ["性能中端", "系统广告", "充电慢"],
        "price_history": {"30d_min": 1799, "30d_avg": 1999, "30d_max": 2099, "lowest_ever": 1699},
        "stock": 1234,
        "delivery": "次日达"
    },
    "iqoo_neo9_032": {
        "product_id": "iqoo_neo9_032",
        "name": "iQOO Neo9 12+256GB 红白魂",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "iQOO",
        "price": 2299,
        "original_price": 2499,
        "discount": "6期免息",
        "shop_id": "shop_iqoo_001",
        "is_official": True,
        "sales_volume": "10万+",
        "rating": 4.6,
        "specs": {"processor": "骁龙8 Gen2", "screen": "6.78英寸 144Hz", "camera": "5000万主摄", "battery": "5160mAh", "weight": "196g", "os": "OriginOS"},
        "tags": ["144Hz", "自研芯片Q1", "120W快充"],
        "good_reviews": ["游戏流畅", "充电快", "性价比高"],
        "bad_reviews": ["塑料中框", "拍照一般", "系统广告"],
        "price_history": {"30d_min": 2099, "30d_avg": 2299, "30d_max": 2399, "lowest_ever": 1999},
        "stock": 1567,
        "delivery": "次日达"
    },
    "honor_90_033": {
        "product_id": "honor_90_033",
        "name": "荣耀90 12+256GB 星钻银",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "荣耀",
        "price": 1899,
        "original_price": 2099,
        "discount": "立减200",
        "shop_id": "shop_honor_001",
        "is_official": True,
        "sales_volume": "12万+",
        "rating": 4.5,
        "specs": {"processor": "骁龙7 Gen1", "screen": "6.7英寸 120Hz", "camera": "2亿像素", "battery": "5000mAh", "weight": "183g", "os": "MagicOS"},
        "tags": ["2亿像素", "3840Hz PWM", "轻薄"],
        "good_reviews": ["屏幕护眼", "拍照清晰", "手感好"],
        "bad_reviews": ["性能一般", "充电慢", "单扬声器"],
        "price_history": {"30d_min": 1699, "30d_avg": 1899, "30d_max": 1999, "lowest_ever": 1599},
        "stock": 876,
        "delivery": "次日达"
    },
    "oppo_k12_034": {
        "product_id": "oppo_k12_034",
        "name": "OPPO K12 8+256GB 青云",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "OPPO",
        "price": 1499,
        "original_price": 1699,
        "discount": "满1499减100",
        "shop_id": "shop_oppo_001",
        "is_official": True,
        "sales_volume": "5万+",
        "rating": 4.4,
        "specs": {"processor": "骁龙7 Gen3", "screen": "6.7英寸 120Hz", "camera": "5000万主摄", "battery": "5500mAh", "weight": "186g", "os": "ColorOS"},
        "tags": ["5500mAh", "100W快充", "抗摔"],
        "good_reviews": ["续航超长", "充电快", "耐摔"],
        "bad_reviews": ["塑料机身", "拍照一般", "性能中等"],
        "price_history": {"30d_min": 1399, "30d_avg": 1499, "30d_max": 1599, "lowest_ever": 1299},
        "stock": 2345,
        "delivery": "次日达"
    },
    "vivo_y100_035": {
        "product_id": "vivo_y100_035",
        "name": "vivo Y100 8+256GB 琉光金",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "vivo",
        "price": 1299,
        "original_price": 1399,
        "discount": "立减100",
        "shop_id": "shop_vivo_001",
        "is_official": True,
        "sales_volume": "8万+",
        "rating": 4.3,
        "specs": {"processor": "骁龙6 Gen1", "screen": "6.64英寸 120Hz", "camera": "6400万主摄", "battery": "5000mAh", "weight": "191g", "os": "OriginOS"},
        "tags": ["5000mAh", "轻薄", "44W快充"],
        "good_reviews": ["续航好", "手感轻", "便宜"],
        "bad_reviews": ["性能一般", "充电慢", "塑料机身"],
        "price_history": {"30d_min": 1199, "30d_avg": 1299, "30d_max": 1349, "lowest_ever": 1099},
        "stock": 1876,
        "delivery": "次日达"
    },
    "xiaomi_civi4_036": {
        "product_id": "xiaomi_civi4_036",
        "name": "小米 Civi 4 Pro 12+256GB 春野绿",
        "category": "手机",
        "sub_category": "智能手机",
        "brand": "小米",
        "price": 2999,
        "original_price": 3299,
        "discount": "赠礼盒",
        "shop_id": "shop_xiaomi_001",
        "is_official": True,
        "sales_volume": "3万+",
        "rating": 4.6,
        "specs": {"processor": "骁龙8s Gen3", "screen": "6.55英寸 1.5K 120Hz", "camera": "5000万徕卡", "battery": "4700mAh", "weight": "179g", "os": "HyperOS"},
        "tags": ["轻薄", "徕卡人像", "金属中框"],
        "good_reviews": ["手感好", "拍照好看", "性能强"],
        "bad_reviews": ["续航一般", "充电慢", "价格略高"],
        "price_history": {"30d_min": 2799, "30d_avg": 2999, "30d_max": 3199, "lowest_ever": 2699},
        "stock": 432,
        "delivery": "次日达"
    },
    "huawei_pocket2_037": {
        "product_id": "huawei_pocket2_037",
        "name": "华为 Pocket 2 12+512GB 洛可可白",
        "category": "手机",
        "sub_category": "折叠屏",
        "brand": "华为",
        "price": 7499,
        "original_price": 7999,
        "discount": "赠皮套",
        "shop_id": "shop_huawei_001",
        "is_official": True,
        "sales_volume": "1万+",
        "rating": 4.7,
        "specs": {"processor": "麒麟9000S", "screen": "6.94英寸折叠屏", "camera": "5000万超感知", "battery": "4520mAh", "weight": "199g", "os": "HarmonyOS 4"},
        "tags": ["竖折", "玄武水滴铰链", "IPX8"],
        "good_reviews": ["小巧", "折叠体验好", "拍照强"],
        "bad_reviews": ["续航一般", "贵", "折痕"],
        "price_history": {"30d_min": 7299, "30d_avg": 7499, "30d_max": 7799, "lowest_ever": 7199},
        "stock": 123,
        "delivery": "预订5天"
    },    


    # ==================== 耳机类 ====================
    "airpods_pro_004": {
        "product_id": "airpods_pro_004",
        "name": "Apple AirPods Pro 2 主动降噪耳机",
        "category": "耳机",
        "sub_category": "真无线降噪",
        "brand": "Apple",
        "price": 1899,
        "original_price": 1999,
        "discount": "无",
        "shop_id": "shop_apple_002",
        "is_official": True,
        "sales_volume": "20万+",
        "rating": 4.9,
        "specs": {
            "type": "入耳式",
            "noise_cancelling": "主动降噪",
            "battery_life": "6小时+30小时充电盒",
            "chip": "H2芯片",
            "waterproof": "IPX4"
        },
        "tags": ["主动降噪", "空间音频", "查找功能"],
        "good_reviews": ["降噪强", "连接稳", "生态好"],
        "bad_reviews": ["贵", "容易掉", "电池衰减快"],
        "price_history": {
            "30d_min": 1799,
            "30d_avg": 1899,
            "30d_max": 1999,
            "lowest_ever": 1699
        },
        "stock": 1023,
        "delivery": "次日达"
    },
    
    "sony_xm5_005": {
        "product_id": "sony_xm5_005",
        "name": "Sony WH-1000XM5 头戴降噪耳机",
        "category": "耳机",
        "sub_category": "头戴降噪",
        "brand": "Sony",
        "price": 2299,
        "original_price": 2899,
        "discount": "满2000减200",
        "shop_id": "shop_sony_001",
        "is_official": True,
        "sales_volume": "3万+",
        "rating": 4.8,
        "specs": {
            "type": "头戴式",
            "noise_cancelling": "旗舰降噪",
            "battery_life": "30小时",
            "driver": "30mm振膜",
            "codec": "LDAC"
        },
        "tags": ["降噪天花板", "佩戴舒适", "30小时续航"],
        "good_reviews": ["降噪无敌", "音质好", "戴着舒服"],
        "bad_reviews": ["夏天热", "收纳盒大", "贵"],
        "price_history": {
            "30d_min": 2099,
            "30d_avg": 2299,
            "30d_max": 2499,
            "lowest_ever": 1999
        },
        "stock": 256,
        "delivery": "明日达"
    },  
    "bose700_038": {
        "product_id": "bose700_038",
        "name": "Bose Noise Cancelling Headphones 700",
        "category": "耳机",
        "sub_category": "头戴降噪",
        "brand": "Bose",
        "price": 2799,
        "original_price": 3199,
        "discount": "满1500减150",
        "shop_id": "shop_bose_001",
        "is_official": True,
        "sales_volume": "1万+",
        "rating": 4.7,
        "specs": {
            "type": "头戴式",
            "noise_cancelling": "11级",
            "battery_life": "20小时",
            "microphone": "8麦克",
            "codec": "AAC"
        },
        "tags": ["通话清晰", "低延迟", "经典舒适"],
        "good_reviews": ["降噪稳", "语音通话好", "做工好"],
        "bad_reviews": ["续航一般", "价格高", "佩戴略紧"],
        "price_history": {"30d_min": 2599, "30d_avg": 2799, "30d_max": 3199, "lowest_ever": 2499},
        "stock": 142,
        "delivery": "次日达"
    },
    "airpods_max_039": {
        "product_id": "airpods_max_039",
        "name": "Apple AirPods Max 空间音频头戴式",
        "category": "耳机",
        "sub_category": "头戴降噪",
        "brand": "Apple",
        "price": 4399,
        "original_price": 4999,
        "discount": "学生优惠200",
        "shop_id": "shop_apple_002",
        "is_official": True,
        "sales_volume": "1.5万+",
        "rating": 4.8,
        "specs": {
            "type": "头戴式",
            "noise_cancelling": "主动降噪",
            "battery_life": "20小时",
            "chip": "H1",
            "codec": "AAC"
        },
        "tags": ["空间音频", "高保真", "铝合金头梁"],
        "good_reviews": ["音质出众", "佩戴舒适", "生态好"],
        "bad_reviews": ["太贵", "体积大", "头梁热"],
        "price_history": {"30d_min": 4199, "30d_avg": 4399, "30d_max": 4799, "lowest_ever": 3999},
        "stock": 75,
        "delivery": "次日达"
    },
    "huawei_freebuds_pro2_040": {
        "product_id": "huawei_freebuds_pro2_040",
        "name": "华为 FreeBuds Pro 2 真无线降噪",
        "category": "耳机",
        "sub_category": "真无线降噪",
        "brand": "华为",
        "price": 899,
        "original_price": 999,
        "discount": "付定金立减50",
        "shop_id": "shop_huawei_001",
        "is_official": True,
        "sales_volume": "8万+",
        "rating": 4.6,
        "specs": {
            "type": "入耳式",
            "noise_cancelling": "主动降噪",
            "battery_life": "6小时+18小时充电盒",
            "driver": "11mm动圈",
            "codec": "LDAC"
        },
        "tags": ["降噪稳", "音质优秀", "全场景降噪"],
        "good_reviews": ["降噪强", "续航好", "连接快"],
        "bad_reviews": ["耳塞不适", "续航一般", "有点贵"],
        "price_history": {"30d_min": 799, "30d_avg": 879, "30d_max": 999, "lowest_ever": 749},
        "stock": 452,
        "delivery": "次日达"
    },
    "xiaomi_buds4_pro_041": {
        "product_id": "xiaomi_buds4_pro_041",
        "name": "小米 Buds 4 Pro 降噪真无线",
        "category": "耳机",
        "sub_category": "真无线降噪",
        "brand": "小米",
        "price": 699,
        "original_price": 799,
        "discount": "领券减50",
        "shop_id": "shop_xiaomi_001",
        "is_official": True,
        "sales_volume": "12万+",
        "rating": 4.6,
        "specs": {
            "type": "入耳式",
            "noise_cancelling": "主动降噪",
            "battery_life": "9小时+24小时充电盒",
            "driver": "11mm",
            "codec": "LHDC"
        },
        "tags": ["高解析", "低延迟", "轻量化"],
        "good_reviews": ["音质好", "降噪稳", "续航长"],
        "bad_reviews": ["调音偏重", "耳塞不适", "降噪噪音"],
        "price_history": {"30d_min": 599, "30d_avg": 669, "30d_max": 799, "lowest_ever": 559},
        "stock": 786,
        "delivery": "次日达"
    },
    "oneplus_buds_z2_042": {
        "product_id": "oneplus_buds_z2_042",
        "name": "一加 Buds Z2 真无线降噪",
        "category": "耳机",
        "sub_category": "真无线降噪",
        "brand": "OnePlus",
        "price": 399,
        "original_price": 499,
        "discount": "满300减30",
        "shop_id": "shop_oneplus_001",
        "is_official": True,
        "sales_volume": "20万+",
        "rating": 4.5,
        "specs": {
            "type": "入耳式",
            "noise_cancelling": "主动降噪",
            "battery_life": "7小时+33小时充电盒",
            "driver": "11mm",
            "codec": "AAC"
        },
        "tags": ["高性价比", "轻量", "长续航"],
        "good_reviews": ["性价比高", "音质不错", "续航长"],
        "bad_reviews": ["降噪一般", "中高音不够", "偶发断连"],
        "price_history": {"30d_min": 349, "30d_avg": 379, "30d_max": 499, "lowest_ever": 329},
        "stock": 1345,
        "delivery": "明日达"
    },
    "sennheiser_momentum_043": {
        "product_id": "sennheiser_momentum_043",
        "name": "森海塞尔 Momentum True Wireless 3",
        "category": "耳机",
        "sub_category": "真无线降噪",
        "brand": "Sennheiser",
        "price": 1699,
        "original_price": 1999,
        "discount": "满1000减100",
        "shop_id": "shop_sennheiser_001",
        "is_official": True,
        "sales_volume": "3万+",
        "rating": 4.7,
        "specs": {
            "type": "入耳式",
            "noise_cancelling": "主动降噪",
            "battery_life": "7小时+28小时充电盒",
            "driver": "7mm动圈",
            "codec": "aptX Adaptive"
        },
        "tags": ["音质旗舰", "低延迟", "三段EQ"],
        "good_reviews": ["音质好", "降噪稳", "佩戴舒服"],
        "bad_reviews": ["贵", "续航一般", "充电慢"],
        "price_history": {"30d_min": 1499, "30d_avg": 1699, "30d_max": 1999, "lowest_ever": 1399},
        "stock": 187,
        "delivery": "明日达"
    },
    "jabra_elite7_044": {
        "product_id": "jabra_elite7_044",
        "name": "Jabra Elite 7 Pro 真无线",
        "category": "耳机",
        "sub_category": "真无线",
        "brand": "Jabra",
        "price": 1299,
        "original_price": 1499,
        "discount": "领券减100",
        "shop_id": "shop_jabra_001",
        "is_official": True,
        "sales_volume": "2.5万+",
        "rating": 4.6,
        "specs": {
            "type": "入耳式",
            "noise_cancelling": "主动降噪",
            "battery_life": "8小时+22小时充电盒",
            "microphone": "4麦克风",
            "codec": "AAC"
        },
        "tags": ["通话强", "防水", "智能降噪"],
        "good_reviews": ["通话清晰", "续航好", "降噪稳"],
        "bad_reviews": ["有线充不方便", "音质稍平", "App复杂"],
        "price_history": {"30d_min": 1099, "30d_avg": 1299, "30d_max": 1499, "lowest_ever": 999},
        "stock": 324,
        "delivery": "次日达"
    },
    "anker_soundcore_045": {
        "product_id": "anker_soundcore_045",
        "name": "Anker Soundcore Liberty 4 Pro",
        "category": "耳机",
        "sub_category": "真无线",
        "brand": "Anker",
        "price": 799,
        "original_price": 899,
        "discount": "限时直降100",
        "shop_id": "shop_anker_001",
        "is_official": True,
        "sales_volume": "10万+",
        "rating": 4.5,
        "specs": {
            "type": "入耳式",
            "noise_cancelling": "主动降噪",
            "battery_life": "8小时+32小时充电盒",
            "driver": "10mm",
            "codec": "LDAC"
        },
        "tags": ["降噪好", "续航长", "性价比"],
        "good_reviews": ["音质好", "续航强", "价格合适"],
        "bad_reviews": ["外放一般", "耳塞不适", "偶发断连"],
        "price_history": {"30d_min": 699, "30d_avg": 769, "30d_max": 899, "lowest_ever": 649},
        "stock": 890,
        "delivery": "次日达"
    },
    "edifier_tws_nb2_046": {
        "product_id": "edifier_tws_nb2_046",
        "name": "漫步者 TWS NB2 真无线降噪",
        "category": "耳机",
        "sub_category": "真无线降噪",
        "brand": "Edifier",
        "price": 499,
        "original_price": 599,
        "discount": "满300减50",
        "shop_id": "shop_edifier_001",
        "is_official": True,
        "sales_volume": "15万+",
        "rating": 4.4,
        "specs": {
            "type": "入耳式",
            "noise_cancelling": "主动降噪",
            "battery_life": "9小时+30小时充电盒",
            "driver": "10mm",
            "codec": "AAC"
        },
        "tags": ["性价比", "续航长", "适合运动"],
        "good_reviews": ["续航好", "音质还行", "降噪不错"],
        "bad_reviews": ["佩戴不稳", "中高频稍尖", "APP不稳定"],
        "price_history": {"30d_min": 429, "30d_avg": 479, "30d_max": 599, "lowest_ever": 399},
        "stock": 1356,
        "delivery": "明日达"
    },
    "libratone_q_adapt_047": {
        "product_id": "libratone_q_adapt_047",
        "name": "Libratone Q Adapt On-Ear 降噪耳机",
        "category": "耳机",
        "sub_category": "头戴降噪",
        "brand": "Libratone",
        "price": 1699,
        "original_price": 1899,
        "discount": "满1000减100",
        "shop_id": "shop_libratone_001",
        "is_official": True,
        "sales_volume": "6000+",
        "rating": 4.5,
        "specs": {
            "type": "头戴式",
            "noise_cancelling": "主动降噪",
            "battery_life": "16小时",
            "driver": "40mm",
            "codec": "AAC"
        },
        "tags": ["轻便", "可折叠", "音质平衡"],
        "good_reviews": ["佩戴舒适", "音质自然", "续航可用"],
        "bad_reviews": ["降噪一般", "做工一般", "稍贵"],
        "price_history": {"30d_min": 1599, "30d_avg": 1699, "30d_max": 1899, "lowest_ever": 1499},
        "stock": 104,
        "delivery": "次日达"
    },
}


# ==================== 店铺信息表 ====================
SHOP_DB = {
    "shop_apple_001": {
        "shop_id": "shop_apple_001",
        "shop_name": "Apple京东自营旗舰店",
        "platform": "京东",
        "fans": "1000万+",
        "score": 4.9,
        "open_years": 8,
        "customer_service": "7x24h",
        "return_policy": "7天无理由",
        "warranty": "全国联保1年"
    },
    "shop_apple_002": {
        "shop_id": "shop_apple_002",
        "shop_name": "Apple京东自营旗舰店",
        "platform": "京东",
        "fans": "1000万+",
        "score": 4.9,
        "open_years": 8,
        "customer_service": "7x24h",
        "return_policy": "7天无理由",
        "warranty": "全国联保1年"
    },
    "shop_apple_003": {
        "shop_id": "shop_apple_003",
        "shop_name": "Apple京东自营旗舰店",
        "platform": "京东",
        "fans": "1000万+",
        "score": 4.9,
        "open_years": 8,
        "customer_service": "7x24h",
        "return_policy": "7天无理由",
        "warranty": "全国联保1年"
    },
    "shop_apple_004": {
        "shop_id": "shop_apple_004",
        "shop_name": "Apple京东自营旗舰店",
        "platform": "京东",
        "fans": "1000万+",
        "score": 4.9,
        "open_years": 8,
        "customer_service": "7x24h",
        "return_policy": "7天无理由",
        "warranty": "全国联保1年"
    },
    "shop_xiaomi_001": {
        "shop_id": "shop_xiaomi_001",
        "shop_name": "小米京东自营旗舰店",
        "platform": "京东",
        "fans": "500万+",
        "score": 4.8,
        "open_years": 6,
        "customer_service": "7x24h",
        "return_policy": "7天无理由",
        "warranty": "全国联保1年"
    },
    "shop_huawei_001": {
        "shop_id": "shop_huawei_001",
        "shop_name": "华为京东自营旗舰店",
        "platform": "京东",
        "fans": "800万+",
        "score": 4.9,
        "open_years": 7,
        "customer_service": "7x24h",
        "return_policy": "7天无理由",
        "warranty": "全国联保1年"
    },
    "shop_sony_001": {
        "shop_id": "shop_sony_001",
        "shop_name": "Sony官方旗舰店",
        "platform": "抖音小店",
        "fans": "200万+",
        "score": 4.7,
        "open_years": 3,
        "customer_service": "9:00-21:00",
        "return_policy": "7天无理由",
        "warranty": "店铺保修1年"
    }
}


# ==================== 用户历史记录（模拟） ====================
USER_HISTORY = {
    "user_123": {
        "user_id": "user_123",
        "view_history": ["iphone15_001", "xiaomi14_002", "huawei60_003"],
        "purchase_history": ["airpods_pro_004"],
        "preferences": {
            "preferred_brands": ["Apple", "小米"],
            "budget_range": [3000, 7000],
            "payment_method": "微信支付"
        },
        "search_history": ["手机 5000左右", "降噪耳机", "MacBook"]
    }
}


# ==================== 辅助函数 ====================

def get_product_by_id(product_id):
    """根据ID获取商品详情"""
    return PRODUCT_DB.get(product_id)

def get_products_by_category(category):
    """根据分类获取商品列表"""
    return {pid: p for pid, p in PRODUCT_DB.items() if p["category"] == category}

def get_products_by_brand(brand):
    """根据品牌获取商品列表"""
    return {pid: p for pid, p in PRODUCT_DB.items() if p["brand"] == brand}

def filter_by_price(max_price):
    """按价格筛选"""
    return {pid: p for pid, p in PRODUCT_DB.items() if p["price"] <= max_price}

def filter_by_price_range(min_price, max_price):
    """按价格区间筛选"""
    return {pid: p for pid, p in PRODUCT_DB.items() if min_price <= p["price"] <= max_price}

def get_shop_info(shop_id):
    """获取店铺信息"""
    return SHOP_DB.get(shop_id)

def compare_products(product_ids):
    """返回对比信息文本（格式化）"""
    products = [PRODUCT_DB[pid] for pid in product_ids if pid in PRODUCT_DB]
    if len(products) < 2:
        return "至少需要两个商品才能对比。"
    result = "📊 商品对比：\n\n"
    for p in products:
        result += f"【{p['name']}】\n"
        result += f"  价格：{p['price']}元\n"
        result += f"  品牌：{p['brand']}\n"
        if "specs" in p:
            result += f"  处理器：{p['specs'].get('processor', '无')}\n"
            result += f"  屏幕：{p['specs'].get('screen', '无')}\n"
            result += f"  摄像头：{p['specs'].get('camera', '无')}\n"
            result += f"  电池：{p['specs'].get('battery', '无')}\n"
        result += "\n"
    # 添加简单对比结论
    min_price = min(p["price"] for p in products)
    max_price = max(p["price"] for p in products)
    result += f"💡 建议：\n  价格范围：{min_price} - {max_price}元\n"
    return result

def get_price_alert(product_id, target_price=0):
    """返回价格分析建议"""
    p = PRODUCT_DB.get(product_id)
    if not p:
        return "商品不存在"
    price = p["price"]
    history = p.get("price_history", {})
    avg_price = history.get("30d_avg", price)
    lowest = history.get("lowest_ever", price)
    if target_price:
        if price <= target_price:
            return f"✅ 当前价格 {price} 元，低于您的心理价位 {target_price} 元，值得购买！"
        else:
            diff = price - target_price
            return f"⚠️ 当前价格 {price} 元，比您的心理价位高 {diff} 元，建议观望。历史最低 {lowest} 元，可设置降价提醒。"
    else:
        # 没有心理价位，给出一般建议
        if price <= avg_price * 0.9:
            return f"✅ 当前价格 {price} 元，低于近30日均价 {avg_price:.0f} 元，建议入手。"
        elif price >= avg_price * 1.1:
            return f"⚠️ 当前价格 {price} 元，高于近30日均价 {avg_price:.0f} 元，建议观望。历史最低 {lowest} 元。"
        else:
            return f"💡 当前价格 {price} 元，处于正常区间。历史最低 {lowest} 元，可以对比一下。"